//////////////////////////////////////////////
//
// MAC_Rpt_four_g_udp.h
//
// aql Ltd
//
// Auth: DLT
//
//////////////////////////////////////////////

// new code for separate SIMCOM, MQTT and UDP modes

#ifndef FOUR_G_UDP_H
#define FOUR_G_UDP_H

#include "MAC_Rpt.h"

void four_g_udp_state_machine(unsigned char *udp_state,unsigned char *prev_udp_state, unsigned char *simcom_state);
void print_udp_state(unsigned char chan);

enum UDP_STATES
{
UDP_NO_COMM_IDLE=0,			// (system WAIT) <= goes to UDP_CHECKS_ERROR_END -> UDP_GET_MODULETYPE:	error_attempts = 0;
// new UDP states
UDP_COMM_INIT_2,
UDP_SET_PDP_2,
UDP_SET_MODE,
UDP_NET_OPEN,
UDP_SOCKET_OPEN,
UDP_SET_RESPONSE,

UDP_COMM_IDLE_2,
UDP_SEND,

UDP_SOCKET_CLOSE,
UDP_NET_CLOSE,

// old MQTT states

// comms init
UDP_COMM_INIT,
UDP_CLOSEALL,
UDP_CHECK_SIG_QUALITY,
UDP_CHECK_4G_NETWORK,
UDP_CHECK_GPRS_NETWORK,
UDP_CHECK_OPS,
UDP_MQTT_CHECK_RELEASE,
UDP_MQTT_CHECK_STOP,
UDP_SET_PDP,
UDP_ACT_PDP,				// 11 THIS STATE NOT USED! error_attempts = 0;

UDP_SET_SSL_CONFIG,
UDP_SET_SSL_AUTHMODE,
UDP_LOAD_SSL_SERVER_CERTIFICATE,
UDP_LOAD_SSL_CLIENT_CERTIFICATE,
UDP_LOAD_SSL_CLIENT_KEY,
UDP_SHOW_SSL_CERTIFICATES,
UDP_SET_SSL_SERVER_CERTIFICATE,
UDP_SET_SSL_CLIENT_CERTIFICATE,
UDP_SET_SSL_CLIENT_KEY,		// WAS error_attempts = 0;

UDP_COMM_START,				// 10 (not a system WAIT) <= goes to UDP_COMMS_INIT_ERROR_END -> UDP_COMM_INIT:	error_attempts = 0;
// connect
UDP_MQTT_ACQUIRE_CLIENT,
UDP_MQTT_SET_WILLTOPIC,
UDP_MQTT_SET_WILLMSG,
UDP_MQTT_SET_UTF8_MODE,		// WAS error_attempts = 0;
UDP_MQTT_CONNECT,			// (not a system WAIT) <= goes to UDP_CONNECT_ERROR_END -> UDP_MQTT_ACQUIRE_CLIENT:	error_attempts = 0;
UDP_MQTT_CONNECT_CHECK,
// send \ receive
UDP_MQTT_SET_SUBSCRIBE_TOPIC,
UDP_MQTT_SUBSCRIBE_TOPIC,
UDP_MQTT_SUBSCRIBE_MSG,
UDP_MQTT_SET_TOPIC,
UDP_MQTT_SET_PAYLOAD,
UDP_MQTT_PUBLISH_MSG,		// 12 WAS error_attempts = 0;

UDP_CONNECT_IDLE,			// (system WAIT) <= goes to UDP_SEND_RCV_ERROR_END -> UDP_MQTT_SET_TOPIC:	error_attempts = 0;
// disconnect
UDP_MQTT_UNSUBSCRIBE_TOPIC,	// > UDP_CONNECT_IDLE goes to UDP_DISC_PWRDOWN_ERROR_END -> UDP_POWER_DOWN_KEY
UDP_MQTT_SERVER_DISCONNECT,
UDP_MQTT_CLIENT_RELEASE,
UDP_MQTT_STOP,

UDP_COMM_IDLE,				//  (system WAIT)

UDP_MQTT_IDLE_CHECK_SIG_QUALITY,

UDP_POWER_UP_ERROR_END,
UDP_CHECKS_ERROR_END,
UDP_COMMS_INIT_ERROR_END,
UDP_CONNECT_ERROR_END,
UDP_SEND_RCV_ERROR_END,
UDP_DISC_PWRDOWN_ERROR_END,
UDP_END,
UDP_NO_ERROR,
UDP_NUM_STATES
};

/*
UDP_SET_PDP
UDP_SET_NONTRANSPARENT
UDP_NET_OPEN
UDP_SOCKET_OPEN
UDP_SET_RESPONSE

UDP_COMM_IDLE
UDP_SEND

UDP_SOCKET_CLOSE
UDP_NET_CLOSE
*/

const char udp_state_str[UDP_NUM_STATES][32] = 
{
//        1         2         3
//234567890123456789012345678901

"NO_COMM_IDLE",

// new UDP states
"COMM_INIT",
"SET_PDP",
"SET_MODE",				// NONTRANSPARENT
"NET_OPEN",
"SOCKET_OPEN",
"SET_RESPONSE",

"COMM_IDLE",
"SEND",

"SOCKET_CLOSE",
"NET_CLOSE",

// old MQTT states

"COMM_INIT",

"CLOSEALL",
"CHECK_SIG_QUALITY",
"CHECK_4G_NETWORK",
"CHECK_GPRS_NETWORK",
"CHECK_OPS",
"MQTT_CHECK_RELEASE",
"MQTT_CHECK_STOP",
"SET_PDP",
"ACT_PDP",						// 11

"SET_SSL_CONFIG",
"SET_SSL_AUTHMODE",
"LOAD_SSL_SERVER_CERTIFICATE",
"LOAD_SSL_CLIENT_CERTIFICATE",
"LOAD_SSL_CLIENT_KEY",
"SHOW_SSL_CERTIFICATES",

"SET_SSL_SERVER_CERTIFICATE",
"SET_SSL_CLIENT_CERTIFICATE",
"SET_SSL_CLIENT_KEY",

"MQTT_COMM_START",				// 10

"MQTT_ACQUIRE_CLIENT",
"MQTT_SET_WILLTOPIC",
"MQTT_SET_WILLMSG",
"MQTT_SET_UTF8_MODE",
"MQTT_CONNECT",
"MQTT_CONNECT_CHECK",
"MQTT_SET_SUBSCRIBE_TOPIC",
"MQTT_SUBSCRIBE_TOPIC",
"MQTT_SUBSCRIBE_MSG",
"MQTT_SET_TOPIC",
"MQTT_SET_PAYLOAD",
"MQTT_PUBLISH_MSG",				// 12

"MQTT_CONNECT_IDLE",

"MQTT_UNSUBSCRIBE_TOPIC",
"MQTT_SERVER_DISCONNECT",
"MQTT_CLIENT_RELEASE",
"MQTT_STOP",

"MQTT_COMM_IDLE",

"MQTT_IDLE_SIG_QUALITY",

"POWER_UP_ERROR",
"CHECKS_ERROR",
"COMMS_INIT_ERROR",
"CONNECT_ERROR",
"SEND_RCV_ERROR",
"DISC_PWRDOWN_ERROR",
"END",
"NO_ERROR"
};

/*
const char nmea_cmd_list[NMEA_CMD_LIST_LENGTH][NMEA_CMD_LIST_ENTRY_LENGTH] = 
{
//234567890
"$PGPPADV",
"$GPGBS",
"$GPGGA",
"$GPGSA"	
};
*/
#define ADDR_AND_PORT_LEN	100





#define FOUR_G_POWER_EN_WAIT		   	   2	// 200msec
#define FOUR_G_RESET_WAIT				   5 	// 500msec
#define FOUR_G_POWER_ON_WAIT			   5 	// 500msec
#define FOUR_G_POWER_ON_RESP_WAIT		 160 	// 16 sec
#define FOUR_G_POWER_DOWN_KEY_WAIT		  25	// 2.5 sec
#define FOUR_G_POWER_DOWN_RESP_WAIT		  10	// 1 sec 	// 260	// 26 sec
#define COMM_DELAY						  20	//10	// 1 sec
#define COMM_TIMEOUT					  20	//10	// 0.5 sec
#define COMM_LONG_TIMEOUT				  40	//20	// 1 sec
#define COMM_VLONG_TIMEOUT				  60	//30	// 1 sec
#define COMM_CERT_TIMEOUT				 100	//40	// 3 sec
#define COMM_PUBLISH_TIMEOUT			 200	//30	// 1 sec
#define COMM_CONN_TIMEOUT				 200	// 3 sec
#define COMM_TIMEOUT_DEFEAT			  0xFFFF	// long as possible...
#define COMM_PHASE_RETRIES				   2	// 1 attempt + 2 retries
#define ERROR_RETRIES				   	   2	// 1 attempt + 2 retries
#define UDP_MAX_ERROR_RETRIES		      10	// 1 attempt + 9 retries

#define UDP_SENSOR_TIME					  30	// 180sec = 3 min

#define UDP_PAYLOAD_SIZE				 8192	// max 10240

#endif