version: '3'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - aqldev
    ports:
      - "80:80"
    volumes:
      - ./hackathon_javascript:/app
    environment:
      - NAME=World
    command: ["python", "hello.py"] # Default script to run

networks:
  aqldev:
    external: true
